### ISSUE TITLE
Are there any examples about multiple concurrent builds (SSR) ?

### ISSUE THREAD

**Issue by yuhaoju** [nuxt/webpackbar#10]
This plugin looks really good for me. I just can't find how to config for multiple concurrent builds. Are there any examples? thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/webpackbar/issues/c8">#c8</a>)</em></sub></div>

**Comment by manniL** [comment]
Nuxt is using `webpackbar` for SSR and CSR builds in its latest `nuxt-edge` releases.

**Comment by OliverJAsh** [comment]
@manniL Can you link to the code example in that project?

**Comment by GriffinSauce** [comment]
I couldn't find the code mentioned but my solution:
```
const configs = [
  {
    plugins: [
      new WebpackBar({ name: 'client' })
    ]
  },
  {
    plugins: [
      new WebpackBar({ name: 'server' })
    ]
  },
]
```
Adding different colours gives you the example in the readme.

**Comment by manniL** [comment]
@GriffinSauce Sorry for the late response!

Nuxt adds the plugin [here](https://github.com/nuxt/nuxt.js/blob/1c34651baabf647c22d81867e3c0f08a9676a5d4/lib/builder/webpack/base.js#L250). It'll be called twice (one time when the client-bundle is compiling, the other time for the server-bundle. This happenes [here](https://github.com/nuxt/nuxt.js/blob/2.x/lib/builder/builder.js#L448)
