### ISSUE TITLE
Bars aren't filling completely before rendering success 

### ISSUE THREAD

**Issue by mherodev** [nuxt/webpackbar#20]
![image](https://user-images.githubusercontent.com/1099139/43220791-c81755ce-8fff-11e8-92fb-5911b767fce0.png)

* Operating System: OSX
* Node Version: 8.11.3
* NPM Version: 5.6
* webpack Version: 4ish
* webpack-serve Version: Unknown

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

https://github.com/lucleray/next-progressbar

### Expected Behavior

Bar to be filled completely

### Actual Behavior

Bars are partially filled before reporting success

### How Do We Reproduce?

https://github.com/lucleray/next-progressbar

**Comment by mherodev** [comment]
This isn't a question, I hate your bot!

**Comment by Atinux** [comment]
Sorry about this, we are improving it, it is still dumb at the moment

**Comment by danieldaeschle** [comment]
Any news on this?
