### ISSUE TITLE
No Stats

### ISSUE THREAD

**Issue by myeveryheart** [nuxt/webpackbar#29]
update to 3.0.0, There's no Stats by Ext or Stats by Loader.
But 2.5.0 is fine.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c22">#c22</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey @myeveryheart. Thanks for reporting. It should be fine with the latest release (3.1.2)

**Comment by MartinCerny-awin** [comment]
I am using the latest version, but I still can't see stats

**Comment by MartinCerny-awin** [comment]
Yes, I do

**Comment by ruiming** [comment]
Same problem with profile on.

**Comment by Airkro** [comment]
same problem in 3.1.3

**Comment by rafaelmaiach** [comment]
Same problem in 3.1.4

**Comment by kevin-atnos** [comment]
Hello,

I have the same problem with 3.1.5, can't see any stat.
Even with profile: true

**Comment by Yohox** [comment]
try to set like this :
`
new WebpackBar({
                reporters: [ 'profile'],
                profile: true
            })
`

**Comment by Airkro** [comment]
@Yohox, It works, but missing table line.
![image](https://user-images.githubusercontent.com/12206891/52690971-5c35a780-2f9a-11e9-8578-6f903365b14b.png)

**Comment by Yohox** [comment]
@Airkro 
we can see https://github.com/nuxt/webpackbar/blob/0c05d65093973058d07faed4b3d2d3e85fa13bbe/src/utils.js

this version use [table](https://www.npmjs.com/package/table) print the table line but now [v3.1.5](https://github.com/nuxt/webpackbar/blob/v3.1.5/src/utils/cli.js) 

the  table pacakge change to  [text-table](https://www.npmjs.com/package/text-table) so it hasn't table line~ if you like this  you can fork it and change the package to text-table~

after that 我们可以说中文

**Comment by kevin-atnos** [comment]
> try to set like this :
> `new WebpackBar({ reporters: [ 'profile'], profile: true })`
> 
> because profile will should when reporters set profile

Hello,

Thank you Yohox for this solution, this is great :)

**Comment by Afanyiyu** [comment]
For using bars reporter and profiler at the same time:

```ts
new Webpackbar({
  reporters: ['fancy', 'profile'],
  profile: true,
}),
```

Tested on `webpackbar@5.0.2`

---

But it's still kinda strange to manually set `reporters` ... The [Options](https://github.com/unjs/webpackbar#options) section in `README.md` mentioned that the `profile` can be used to "enable profiler" but it doesn't actually do it. I'll create a PR to fix this.
