### ISSUE TITLE
Don't run in CI

### ISSUE THREAD

**Issue by hipstersmoothie** [nuxt/webpackbar#4]
When the progress bar runs in my CI (jenkins) it produces an insane amount of output. Maybe you could use the package 'isCi' to disable the progress bar in the CI environment 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/webpackbar/issues/c4">#c4</a>)</em></sub></div>

**Comment by pi0** [comment]
Yeah. It's already shipped in 1.3.0 ;)
https://github.com/nuxt/webpackbar/blob/master/CHANGELOG.md
