### ISSUE TITLE
Progress Bar Closes Before Compilation Completes

### ISSUE THREAD

**Issue by dtothefp** [nuxt/webpackbar#9]
* Operating System: OSX Sierra
* Node Version: 8.11.0
* NPM Version: 5.6.0
* webpack Version: 3x & 4x
* webpack-serve Version: 2x & 3x

This issue is for a:

-  [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
```js
const app = new DevServer(compiler, serverOptions);

let hasRun = false;

app.middleware.waitUntilValid(() => {
  if (!hasRun) {
    app.listen(hotPort, host, (err) => {});
  }
});
```
 
or 
```js
compiler.run(() => {});
```
##### webpack.config.js
https://gist.github.com/dtothefp/7769a27293cf771dbd60fe46dcc99c3c

### Expected Behavior
When progress bar finishes Webpack compilation finishes and task proceeds

### Actual Behavior
Progress bar finishes and task hangs while webpack does some unknown work behind the scenes.

### How Do We Reproduce?
This is most likely not an issue with webpackbar but with Webpack itself. I'm putting this issue here to gain clarity on what is happening so I can put an issue up on Webpack with pertinent information. 

I'm using `app.middleware.waitUntilValid` to signal task completion although I've tried using `compiler.hooks.done.tap` or v3 `compiler.plugin('done'`. I see this same code in the webpackbar source but it seems the progress bar shows compilation completion well before the callback for `done` is called. I have a large app and completion of the initial build takes about 1min although subsequent reloads with WebpackDevServer or `compiler.watch` show completion in the progress bar in about 4s. Unfortunately, after progress bar completes a typical wait time for calling of the `done` callback is at least 30s. I'd like to understand this issue greater so I can figure out where the bottlenecks are in my Webpack build are as I'm trying to increase performance.

**Comment by pi0** [comment]
Hey @dtothefp sorry for opening this issue for a long time. We have made several improvements on [v3.0.0](https://github.com/nuxt/webpackbar/releases/tag/v3.0.0) that should resolve the 100% state not being shown.
